spring:
  data:
    mongodb:
      port: 27018
      database: FileManagement
      host: localhost

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351

server:
  port: 3100

web:
  cors:
    allowed-origins: "http://localhost:8080"
    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
    max-age: 3600
    allowed-headers: "Requestor-Type"
    exposed-headers: "X-Get-Header"